version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  matrix:
    - CLI_VERSION: 1.0.0-preview2-1-0031771
    - CLI_VERSION: Latest

install:
  # .NET Core SDK binaries
  - ps: $url = "https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
  # follow normal installation from binaries
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\Bayes" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
test_script:
- dotnet test "test\Bayes.Tests" -c %CONFIGURATION%